package com.huaxia.test.bean;
// Generated 2017-2-27 17:02:28 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CountriesId generated by hbm2java
 */
@Embeddable
public class CountriesId  implements java.io.Serializable {


     private String code;
     private int year;
     private BigDecimal gdpPerCapita;
     private BigDecimal govtDebt;

    public CountriesId() {
    }

    public CountriesId(String code, int year, BigDecimal gdpPerCapita, BigDecimal govtDebt) {
       this.code = code;
       this.year = year;
       this.gdpPerCapita = gdpPerCapita;
       this.govtDebt = govtDebt;
    }
   

    @Column(name="code", nullable=false, length=2)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Column(name="year", nullable=false)
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }

    @Column(name="gdp_per_capita", nullable=false, precision=10)
    public BigDecimal getGdpPerCapita() {
        return this.gdpPerCapita;
    }
    
    public void setGdpPerCapita(BigDecimal gdpPerCapita) {
        this.gdpPerCapita = gdpPerCapita;
    }

    @Column(name="govt_debt", nullable=false, precision=10)
    public BigDecimal getGovtDebt() {
        return this.govtDebt;
    }
    
    public void setGovtDebt(BigDecimal govtDebt) {
        this.govtDebt = govtDebt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CountriesId) ) return false;
		 CountriesId castOther = ( CountriesId ) other; 
         
		 return ( (this.getCode()==castOther.getCode()) || ( this.getCode()!=null && castOther.getCode()!=null && this.getCode().equals(castOther.getCode()) ) )
 && (this.getYear()==castOther.getYear())
 && ( (this.getGdpPerCapita()==castOther.getGdpPerCapita()) || ( this.getGdpPerCapita()!=null && castOther.getGdpPerCapita()!=null && this.getGdpPerCapita().equals(castOther.getGdpPerCapita()) ) )
 && ( (this.getGovtDebt()==castOther.getGovtDebt()) || ( this.getGovtDebt()!=null && castOther.getGovtDebt()!=null && this.getGovtDebt().equals(castOther.getGovtDebt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCode() == null ? 0 : this.getCode().hashCode() );
         result = 37 * result + this.getYear();
         result = 37 * result + ( getGdpPerCapita() == null ? 0 : this.getGdpPerCapita().hashCode() );
         result = 37 * result + ( getGovtDebt() == null ? 0 : this.getGovtDebt().hashCode() );
         return result;
   }   


}


