package com.huaxia.test.bean;
// Generated 2017-2-27 17:02:28 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dd generated by hbm2java
 */
@Entity
@Table(name="dd"
    ,catalog="test"
)
public class Dd  implements java.io.Serializable {


     private int id;
     private String name;

    public Dd() {
    }

	
    public Dd(int id) {
        this.id = id;
    }
    public Dd(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


