package com.huaxia.test.bean;
// Generated 2017-2-27 17:02:28 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Host generated by hbm2java
 */
@Entity
@Table(name="host"
    ,catalog="test"
)
public class Host  implements java.io.Serializable {


     private Integer hostId;
     private Integer userId;
     private String hostName;
     private String ipAddress;

    public Host() {
    }

	
    public Host(String hostName) {
        this.hostName = hostName;
    }
    public Host(Integer userId, String hostName, String ipAddress) {
       this.userId = userId;
       this.hostName = hostName;
       this.ipAddress = ipAddress;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="host_id", unique=true, nullable=false)
    public Integer getHostId() {
        return this.hostId;
    }
    
    public void setHostId(Integer hostId) {
        this.hostId = hostId;
    }
    
    @Column(name="user_id")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    
    @Column(name="host_name", nullable=false, length=50)
    public String getHostName() {
        return this.hostName;
    }
    
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }
    
    @Column(name="ip_address", length=50)
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }




}


