package com.huaxia.test.bean;
// Generated 2017-2-27 17:02:28 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RoleUser generated by hbm2java
 */
@Entity
@Table(name="role_user"
    ,catalog="test"
)
public class RoleUser  implements java.io.Serializable {


     private RoleUserId id;

    public RoleUser() {
    }

    public RoleUser(RoleUserId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="roleId", column=@Column(name="role_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ) } )
    public RoleUserId getId() {
        return this.id;
    }
    
    public void setId(RoleUserId id) {
        this.id = id;
    }




}


